### ISSUE TITLE
backpress click to 2nd tooltip close and 1st tooltip open

### ISSUE THREAD

**Issue by harshipatelb** [douglasjunior/android-simple-tooltip#49] opened 2017-07-19 09:38 UTC
i have 2 tooltip. 2nd tooltip opens by 1st tooltip button click. all working good.
now i want to close 2nd tooltip on pressing back button and display 1st one java.lang.IllegalArgumentException: Tooltip has ben dismissed.?

**Comment by douglasjunior** [comment] 2017-07-19 10:59
Do you want to re-open the first tooltip? You should do this with `Builder`. 

Save the `Builder` reference to create as many times as you want.

```java
SimpleTooltip.Builder builder1 = new SimpleTooltip.Builder(context)
    .anchorView(yourView)
    .text("Tooltip text")
    .gravity(Gravity.END)
    .animated(true)
    .transparentOverlay(false);

// build a tooltip
SimpleTooltip tooltip1 = builder1.build();
tooltip1.show();

// after tooltip1 is dismissed, create tooltip1 again.
SimpleTooltip tooltip1again = builder1.build();
tooltip1again.show();
```

**Comment by harshipatelb** [comment] 2017-07-19 12:26
///Error
 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
=================================================================== 


private android.widget.Button btn;
    SimpleTooltip.Builder builder1 ;
    SimpleTooltip tooltip1;
    Context context;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        context=getApplicationContext();

        this.btn = (Button) findViewById(R.id.btn);
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                builder1 = new SimpleTooltip.Builder(context)
                        .anchorView(v)
                        .text("Tooltip text")
                        .contentView(R.layout.tooltipfff)
                        .gravity(Gravity.BOTTOM)
                        .transparentOverlay(false);


                tooltip1 = builder1.build();
                tooltip1.show();

            }
        });
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        SimpleTooltip tooltip2=builder1.build();
        tooltip2.show();
    }

}

**Comment by harshipatelb** [comment] 2017-07-19 12:32
Error
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
```
```java
 private android.widget.Button btn;
    SimpleTooltip.Builder builder1 ;
    SimpleTooltip tooltip1, tooltip2;
    Context context;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        context=getApplicationContext();
        builder1 = new SimpleTooltip.Builder(context);
        this.btn = (Button) findViewById(R.id.btn);
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                builder1 = new SimpleTooltip.Builder(context)
                        .anchorView(v)
                        .text("Tooltip text")
                        .contentView(R.layout.tooltipfff)
                        .gravity(Gravity.BOTTOM)
                        .transparentOverlay(false);

                // build a tooltip
                tooltip1 = builder1.build();
                tooltip1.show();
                tooltip1.findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v2) {
                        if(tooltip1.isShowing())
                            tooltip1.dismiss();
                        SimpleTooltip.Builder sec=new SimpleTooltip.Builder(context)
                                .anchorView(v)
                                .text("Tooltip text")
                                .contentView(R.layout.sec)
                                .gravity(Gravity.BOTTOM);
                        tooltip2 = sec.build();
                        tooltip2.show();
                    }
                });

            }
        });
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        if(tooltip2.isShowing())
        {
            tooltip2.dismiss();
        SimpleTooltip tooltip3=builder1.build();
        tooltip3.show();
    }
    }
}
```

**Comment by douglasjunior** [comment] 2017-07-19 13:19
I do not know if I understand what you need, but in `onBackPress` you should not close Tooltip2 and re-open Tooltip1? The problem is in your logic. You are not closing Tooltip2 and you are trying to open Tooltip1 at the same time.

This Tooltip is based on the PopupWindow. I recommend you [learn more](https://www.google.com.br/search?client=opera&q=android+popupwindow&sourceid=opera&ie=UTF-8&oe=UTF-8) about how PopupWindow works on Android.

**Comment by harshipatelb** [comment] 2017-07-20 03:46
The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by harshipatelb** [comment] 2017-07-20 06:30
Thank you @douglasjunior

**Closed as completed** 2017-07-20 10:49 UTC
Labels: question
