### ISSUE TITLE
SimpleTooltip.java line 354, mPopupWindow.getContentView(): mPopupWindow is null

### ISSUE THREAD

**Issue by AdrianMeizoso** [douglasjunior/android-simple-tooltip#11] opened 2016-07-11 11:15 UTC
The issue is as follows:

`Fatal Exception: java.lang.NullPointerException`.

The stack trace:

```
io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip$9.onGlobalLayout(SimpleTooltip.java:483)
android.view.ViewTreeObserver.dispatchOnGlobalLayout (ViewTreeObserver.java:667)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2048)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1181)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:4943)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:776)
```

I don't know exactly how this occur. This issue could be fixed checking whether mPopupWindow is shown or null.

**Comment by douglasjunior** [comment] 2016-07-11 12:23
I cant ignore this situation without knowing the cause of the problem, because it can hide something more serious in the future. The questions is: the `popupwindow` should not be null at this point.

What is the version you are using? `0.1.1` or `SNAPSHOT`?

**Comment by AdrianMeizoso** [comment] 2016-07-11 13:23
I'm using version `0.1.1`.

**Comment by douglasjunior** [comment] 2016-07-14 11:25
I did one change to test this problem. Please, try with [branch issue-11](https://github.com/douglasjunior/android-simple-tooltip/tree/issue-11)

or using

``` gradle
compile 'com.github.douglasjunior:android-simple-tooltip:issue-11-SNAPSHOT'
```

**Comment by AdrianMeizoso** [comment] 2016-07-27 08:34
It's seems that this issue is resolved with the branch issue-11

**Comment by AdrianMeizoso** [comment] 2016-07-27 08:38
Thanks for your support 👍

**Comment by douglasjunior** [comment] 2016-07-27 11:04
Great 🎉 , thanks for feedback. 😄 

This is only for test, I will fix this now.

**Comment by se-rg-os** [comment] 2016-07-27 12:24
@douglasjunior first of all thanks for the awesome library! 👍 

I am using your code with small modifications, and faced this issue as well. 
I have found that exactly `mAnimationListener` is failing with NPE because it is run after `mAutoDismissLayoutListener` which invokes `dismiss()` method and popup is assigned to null (as I have seen from the fix as well).

Do you think it would be good to change `TooltipUtils.removeOnGlobalLayoutListener (View, ViewTreeObserver.OnGlobalLayoutListener)` to `TooltipUtils.removeOnGlobalLayoutListener (PopupWindow, ViewTreeObserver.OnGlobalLayoutListener)` and in this new method to check if popup is not null and its contentView is not null and only then remove listener?

**Comment by douglasjunior** [comment] 2016-07-27 12:41
I'm happy to know it's useful, thanks for feedback. 😃 

I'll look at it the next time. Some of these listeners must continue working even after dismiss. As in the case of interrupting the animation. However, they need to be removed also.

There is a great chance to happen memory leak if you're not careful. I think only check `popupwindow == null` is not a good option.

**Comment by se-rg-os** [comment] 2016-07-27 13:02
Agree on chance of memory leak. Maybe then mAnimationListener (and/or any other needed listeners) may be removed directly in onDismiss() callback before mPopupWindow is assigned to null?

In general this case happens for me when I try to show tooltip very close to time when the`onPause()` of my activity is called (when user leaves the app). 

Then I am getting such a flow in the logs (added some info about which listener is run and what is the value for mPopupWindow:

```
 14:50:08.790  D/TestActivity: onStart()
 14:50:08.800  D/TestActivity: onResume
 14:50:11.110  D/TestActivity: onPause
 14:50:11.170  D/TestActivity: Show tooltip
 14:50:11.220  D/Tooltip: build
 14:50:11.220  D/Tooltip: init()
 14:50:11.220  D/Tooltip: configPopupWindow()
 14:50:11.220  D/Tooltip: configPopupWindow(): android.widget.PopupWindow@2d171785 
 14:50:11.560  D/Tooltip: LocationLayoutListener android.widget.PopupWindow@2d171785
 14:50:11.570  D/Tooltip: AutoDismissLayoutListener android.widget.PopupWindow@2d171785
 14:50:11.610  D/TestActivity: onStop 
 14:50:11.670  D/Tooltip: AutoDismissLayoutListener android.widget.PopupWindow@2d171785
 14:50:11.670  D/Tooltip: dismiss()
 14:50:11.670  D/Tooltip: ArrowLayoutListener null
```

I've tried managing not to show tooltip after `TestActivity.onPause()` is run, but then still it may happen so that Showing tooltip and onPause() are really close in time and there is race condition between onPause() and actually presenting/dismissing tooltip. As you can see now, I got `ArrowLayoutListener` run after dismiss(). If you have any advice how this can be fixed in a smarter/safer way, please let me know. Or is not assigning mPopupWindow to null in `onDismiss()` safe enough?

**Comment by douglasjunior** [comment] 2016-07-27 14:58
Thanks for your information, it saved me time.

I'm looking at it now. So, apparently who is causing the problem is the `mAutoDismissLayoutListener`, that's good, because it is doing his job. 

This problem can really happen because the listeners are asynchronous. 

So, I think it would have to leave `mPopupWindow = null` to avoid memory leak when the developer, for some reason, hold a reference to the Tooltip.

Thus, the solution I can think of at the moment is to remove all listeners when the `onDismiss` happen. Like your first suggestion.

``` java
    @Override
    public void onDismiss() {
        //...
        SimpleTooltipUtils.removeOnGlobalLayoutListener(mPopupWindow.getContentView(), mLocationLayoutListener);
        SimpleTooltipUtils.removeOnGlobalLayoutListener(mPopupWindow.getContentView(), mArrowLayoutListener);
        SimpleTooltipUtils.removeOnGlobalLayoutListener(mPopupWindow.getContentView(), mShowLayoutListener);
        SimpleTooltipUtils.removeOnGlobalLayoutListener(mPopupWindow.getContentView(), mAnimationLayoutListener);
        SimpleTooltipUtils.removeOnGlobalLayoutListener(mPopupWindow.getContentView(), mAutoDismissLayoutListener);

        mPopupWindow = null;
    }
```

I will send a commit to [branch issue-11](https://github.com/douglasjunior/android-simple-tooltip/tree/issue-11) now.

**Comment by douglasjunior** [comment] 2016-07-28 11:23
@AdrianMeizoso You can try again with the new changes, please?

To force the Gradle to update your library, use the `changing=true` param.

``` gradle
dependencies {
    // ...
    compile ('com.github.douglasjunior:android-simple-tooltip:issue-11-SNAPSHOT') {
        changing = true // Gradle will then check for updates every 24 hours
    }
}
```

**Closed as completed** 2016-08-15 19:05 UTC
Labels: bug, awaiting feedback
